#!/bin/bash
#
#
#
############################
#
#
#AUTHER :NIKHIL
#VERSION : V1
#date :22 aug 2024
#calculater
#
#
############################
#
#
#
number1=a
number2=b
echo "enter the first number"
read a
echo "enter the second number"
read b
echo "choose the calculation"
echo "1.add \n 2.Divied \n 3.Multiply \n 4.Substract \n"

read choos

case $choos in
        add)echo "$a+$b" | bc;;
        Divied)echo "$a/$b" | bc;;
        Multiply)echo "$a*$b" | bc;;
        Substract)echo "$a-$b" | bc;;
esac
